---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-cluster
  region: eu-west-2
  version: "1.19"

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 1
  ssh:
    allow: true
    publicKeyName: capstone

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]